imports:
    - php

filter:
    excluded_paths: [vendor/*, test/*, setup/*]

build:

    dependencies:
        before:
            -
                command: "mkdir build"

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

checks:
    php:
        code_rating: true
        duplication: true
